apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The Gogs server's http port
  name: gogs
  namespace: {{ .Values.gogs.namespace }}
spec:
  selector:
    app: gogs
  ports:
    - name: 3000-tcp
      protocol: TCP
      port: 3000
      targetPort: 3000