kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gogs-postgres-data
  namespace: '{{ .Values.gogs.namespace }}'
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: gogs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
