apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The Gogs server's http port
  name: gogs
  namespace: {{ .Values.gogs.namespace }}
spec:
  selector:
    app: gogs
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432