kind: ConfigMap
apiVersion: v1
metadata:
  name: gogs-config
  namespace: {{ .Values.gogs.namespace }}
  labels:
    app: gogs
data:
  app.ini: |
    RUN_MODE = prod
    RUN_USER = gogs

    [database]
    DB_TYPE  = postgres
    HOST     = gogs-postgresql:5432
    NAME     = gogs
    USER     = gogs
    PASSWD   = gogs

    [repository]
    ROOT = /opt/gogs/data/repositories

    [server]
    ROOT_URL=http://gogs-{{ .Values.gogs.namespace }}.{{ .Values.gogs.wildcard }}
    SSH_DOMAIN=gogs-{{ .Values.gogs.namespace }}.{{ .Values.gogs.wildcard }}

    [security]
    INSTALL_LOCK = true

    [service]
    ENABLE_CAPTCHA = false

    [webhook]
    SKIP_TLS_VERIFY = false