{{- range untilStep 1 (int .Values.Users) 1 }}
{{ $n := . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user{{$n}}-openshift-gitops-openshift-gitops-argocd-server
  labels:
    app.kubernetes.io/managed-by: user{{$n}}-openshift-gitops
    app.kubernetes.io/name: user{{$n}}-openshift-gitops
    app.kubernetes.io/part-of: argocd
  annotations:
    argocds.argoproj.io/name: user{{$n}}-openshift-gitops
    argocds.argoproj.io/namespace: user{{$n}}-openshift-gitops
rules:
  - verbs:
      - get
      - delete
      - patch
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - events

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user{{$n}}-openshift-gitops-openshift-gitops-argocd-application-controller
  labels:
    app.kubernetes.io/managed-by: user{{$n}}-openshift-gitops
    app.kubernetes.io/name: user{{$n}}-openshift-gitops
    app.kubernetes.io/part-of: argocd
  annotations:
    argocds.argoproj.io/name: user{{$n}}-openshift-gitops
    argocds.argoproj.io/namespace: user{{$n}}-openshift-gitops
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - get
      - list
    nonResourceURLs:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - operators.coreos.com
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - operator.openshift.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - user.openshift.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - config.openshift.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - console.openshift.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - namespaces
      - persistentvolumeclaims
      - persistentvolumes
      - configmaps
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - storage.k8s.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - machine.openshift.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - machineconfig.openshift.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - compliance.openshift.io
    resources:
      - scansettingbindings

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user{{$n}}-openshift-gitops-openshift-gitops-argocd-application-controller
  labels:
    app.kubernetes.io/managed-by: user{{$n}}-openshift-gitops
    app.kubernetes.io/name: user{{$n}}-argocd-application-controller
    app.kubernetes.io/part-of: argocd
  annotations:
    argocds.argoproj.io/name: user{{$n}}-openshift-gitops
    argocds.argoproj.io/namespace: user{{$n}}-openshift-gitops
subjects:
  - kind: ServiceAccount
    name: user{{$n}}-openshift-gitops-argocd-application-controller
    namespace: user{{$n}}-openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user{{$n}}-openshift-gitops-openshift-gitops-argocd-application-controller

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user{{$n}}-openshift-gitops-argocd-application-controller_edit_role
  namespace: user{{$n}}-petclinic
subjects:
  - kind: ServiceAccount
    name: user{{$n}}-openshift-gitops-argocd-application-controller
    namespace: user{{$n}}-openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
{{- end }}